<?php include 'header.php'; ?>
<?php include 'welcome.php'; ?>
<?php include 'populartour.php'; ?>
<?php include 'services.php'; ?>
<?php include 'customerfeedback.php'; ?>
<?php include 'aboutus.php'; ?>
<?php include 'contactus.php'; ?>
<?php include 'floating_announcement.php'; ?>
<?php include 'footer.php'; ?>
